POST http://localhost:1234/users/login
Content-Type: application/json

{
    "email": "g.g.pascucci@gmail.com",
    "password": "p4sk1234"
}

###

POST http://localhost:1234/users/login
Content-Type: application/json

{
    "firstname": "Luca",
    "lastname": "Modric",
    "username": "luquitak3_",
    "email": "lucamodric12_@ggayl.es",
    "password": "modric10abc"
}

###