POST http://localhost:1234/users/signup
Content-Type: application/json

{
    "email": "algoejemplo@twnty.com",
    "password": "Algo mas"
}

###

POST http://localhost:1234/users/signup
Content-Type: application/json

{

}

###

POST http://localhost:1234/users/signup
Content-Type: application/json

{
    "firstname": "Guido",
    "lastname": "Pascucci",
    "username": "gp4s444",
    "email": "g.g.pascucci@gmail.com",
    "password": "p4sk1234"
}

###

POST http://localhost:1234/users/signup
Content-Type: application/json

{
    "firstname": "Marcos",
    "lastname": "Paz",
    "username": "marqus11",
    "email": "mar.cks1@gmail.com",
    "password": "m1a2k43"
}

###
